added pro guard rule so we dont run into that weird samsung 4.2.2 error - check this for more details http://stackoverflow.com/questions/24809580/noclassdeffounderror-android-support-v7-internal-view-menu-menubuilder